### ISSUE TITLE
Move contributing guidelines to Pelican docs

### ISSUE THREAD

**Issue by oulenz** [getpelican/cookiecutter-pelican-plugin#4]
As it stands, this template includes identical, very detailed contributing guidelines into every plugin created with it. Wouldn't those guidelines be easier to maintain in the pelican docs (with a link in the plugin readme)?

**Comment by justinmayer** [comment]
You raise a very good point. I think that may indeed scale better.

**Comment by davidag** [comment]
It looks like a very good idea. The smaller the template, the easier and less frequently it will need to be updated in dozens of repositories.

**Comment by justinmayer** [comment]
I submitted a PR to replace the duplicated Contributing docs with a link to the canonical version in Pelican's documentation.
