### ISSUE TITLE
"dev_status" should be a list of choices

### ISSUE THREAD

**Issue by ivanhercaz** [getpelican/cookiecutter-pelican-plugin#7]
Hi!
I found this cookicutter template and I already used it to generate the scheme for a plugin I am developing.

https://github.com/getpelican/cookiecutter-pelican-plugin/blob/1295850178e0ea636d2a80a6ed1827cc693dd4c1/cookiecutter.json#L14

However, in the current code of `cookiecutter.json` the question`dev_status` raises me some doubts:

  1. Should it be a list of choices?
  2. I think the example, or the list of choices if you are agree with the first point, should contain: "development", "production/stable".
  3. Why is there a "5" in the `dev_status` example?

**Comment by avaris** [comment]
> Why is there a "5" in the dev_status example?

https://pypi.org/classifiers/

**Comment by justinmayer** [comment]
Enumerated list of choices probably makes the most sense, so I made that change.

**Comment by ivanhercaz** [comment]
@avaris oh, thank you! I didn't think about them.

@justinmayer, really nice!
